flags: {}
packages:
- '.'

### Uncoment the resolver you want to use and re-run `stack build/test/bench`.
# resolver: lts-10.0
resolver: lts-9.20

### ChasingBottoms is only in Stackage snapshots lts-7.24 and below.
extra-deps:
- ChasingBottoms-1.3.1.3
