flags: {}
packages:
# - containers  # Unnecessary for development. Uncomment to produce an sdist or similar.
- containers-tests

### Uncoment the resolver you want to use and re-run `stack build/test/bench`.
# resolver: lts-10.0
resolver: lts-12.26
