name: i386 CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run:
    shell: bash

jobs:
  # i386 is 32-bit
  i386:
    runs-on: ubuntu-latest
    container:
      image: i386/ubuntu:bionic
    steps:
    - name: Install
      # Install GHC via apt because GHCup currently fails.
      run: |
        apt-get update -y
        apt-get install -y ghc cabal-install
    - uses: actions/checkout@v1 # This version must stay old enough to remain compatible with the container image
    - name: Test
      run: |
        ghc --version
        cabal --version
        cabal update
        cabal build all:tests  # Workaround for https://github.com/haskell/cabal/issues/11677
        cabal test all
